import json
from pathlib import Path

import pytest

from build_workflow import build_workflow

REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = REPO_ROOT / "shiva.config.yml"


@pytest.fixture(scope="module")
def workflow():
    return build_workflow(CONFIG_PATH)


@pytest.fixture(scope="module")
def agent_workflow():
    return build_workflow(CONFIG_PATH, agent=True)


def node_by_type(workflow, node_type):
    return [n for n in workflow["nodes"] if n["type"] == node_type]


def test_workflow_is_json_serializable(workflow):
    json.dumps(workflow)


def test_has_expected_nodes(workflow):
    types = [n["type"] for n in workflow["nodes"]]
    assert "n8n-nodes-base.webhook" in types
    assert types.count("n8n-nodes-base.httpRequest") == 3  # fetch files, LLM, post comment
    assert types.count("n8n-nodes-base.code") == 2  # check skip, build prompt
    assert "n8n-nodes-base.if" in types


def test_nodes_are_connected_in_a_chain(workflow):
    connections = workflow["connections"]
    names = {n["name"] for n in workflow["nodes"]}
    for source, targets in connections.items():
        assert source in names
        for branch in targets["main"]:
            for target in branch:
                assert target["node"] in names
    # every node except the last one has an outgoing connection
    assert len(connections) == len(workflow["nodes"]) - 1


def test_skip_check_runs_before_any_github_call(workflow):
    """00010: draft / skip-review PRs are dropped before Fetch PR Files."""
    connections = workflow["connections"]
    check = connections["GitHub PR Webhook"]["main"][0][0]["node"]
    assert check == "Check Skip Conditions"
    assert connections["Check Skip Conditions"]["main"][0][0]["node"] == "Skip Draft & Labeled PRs?"
    if_branches = connections["Skip Draft & Labeled PRs?"]["main"]
    assert if_branches[0][0]["node"] == "Fetch PR Files"  # true branch: continue
    assert if_branches[1] == []  # false branch: stop, no review


def test_check_skip_node_embeds_tested_predicate(workflow):
    check = next(n for n in workflow["nodes"] if n["name"] == "Check Skip Conditions")
    script = check["parameters"]["pythonCode"]
    assert check["parameters"]["language"] == "python"
    assert "def should_skip_pr(" in script
    assert "skip-review" in script
    # the reviewable-action allowlist must travel with the predicate
    assert "REVIEWABLE_ACTIONS" in script
    assert "ready_for_review" in script
    # the webhook body must be passed through for downstream $json.body expressions
    assert '"body"' in script


def test_if_node_routes_on_computed_skip_flag(workflow):
    if_node = node_by_type(workflow, "n8n-nodes-base.if")[0]
    conditions = if_node["parameters"]["conditions"]["conditions"]
    assert len(conditions) == 1
    assert conditions[0]["leftValue"] == "={{ $json.skip }}"
    assert conditions[0]["operator"] == {"type": "boolean", "operation": "false", "singleValue": True}


def test_python_nodes_use_native_runner_api(workflow):
    """n8n's native Python task runner exposes `_items` only; `_input` is
    the removed Pyodide API and fails at runtime with NameError."""
    for node in node_by_type(workflow, "n8n-nodes-base.code"):
        script = node["parameters"]["pythonCode"]
        assert "_items" in script, node["name"]
        assert "_input" not in script, node["name"]


def test_code_node_embeds_only_enabled_categories(workflow):
    code = next(n for n in workflow["nodes"] if n["name"] == "Filter Diff & Build Prompt")
    script = code["parameters"]["pythonCode"]
    for name in [
        "Structural Review",
        "Logical Review",
        "Behavioral Review",
        "Security Review",
        "Performance Review",
    ]:
        assert name in script
    for name in [
        "Code Style Review",
        "Docstrings and Comments Review",
        "Messages Review",
        "Test Coverage Review",
    ]:
        assert name not in script


def test_node_positions_are_derived_from_list_index(workflow):
    """Canvas positions are a function of order (220 * i), not hand-maintained
    literals, so inserting a node never requires rewriting downstream ones."""
    for i, node in enumerate(workflow["nodes"]):
        assert node["position"] == [220 * i, 0], node["name"]


def test_code_nodes_share_the_generated_template(workflow):
    """Both Python Code nodes are produced by one render helper, so the header,
    the native-runner comment, and the glue stay identical across them."""
    header = "# Generated by scripts/build_workflow.py — do not edit here."
    runner_comment = "# n8n native Python runner exposes input as `_items` (plain dicts)."
    for node in node_by_type(workflow, "n8n-nodes-base.code"):
        script = node["parameters"]["pythonCode"]
        assert script.startswith(header + "\n"), node["name"]
        assert runner_comment in script, node["name"]


def test_build_with_repo_override_merges_categories(tmp_path):
    """00014: a per-repo override file is merged over the defaults by id —
    disabled defaults drop out of the embedded prompt, new categories appear."""
    override = tmp_path / ".shiva.yml"
    override.write_text(
        "categories:\n"
        "  - id: performance\n"
        "    enabled: false\n"
        "  - id: i18n\n"
        "    name: Internationalization Review\n"
        "    enabled: true\n"
        "    prompt: Check that user-facing strings are translated.\n"
    )
    workflow = build_workflow(CONFIG_PATH, override_path=override)
    code = next(n for n in workflow["nodes"] if n["name"] == "Filter Diff & Build Prompt")
    script = code["parameters"]["pythonCode"]
    assert "Internationalization Review" in script  # custom category added
    assert "Performance Review" not in script  # default disabled by the override
    assert "Structural Review" in script  # other defaults untouched


def test_build_without_override_matches_default():
    """Passing no override must not change the generated workflow."""
    assert build_workflow(CONFIG_PATH) == build_workflow(CONFIG_PATH, override_path=None)


def test_code_node_embeds_tuned_prompt_scaffolding(workflow):
    """00012: severity scale and structured output format travel with the
    embedded build_review_prompt so the runtime prompt is fully specified."""
    code = next(n for n in workflow["nodes"] if n["name"] == "Filter Diff & Build Prompt")
    script = code["parameters"]["pythonCode"]
    assert "Severity levels" in script
    assert "Output format" in script
    assert "Verdict" in script
    # conventions are wired through, defaulting to the repo's configured value
    assert "CONVENTIONS" in script
    assert "conventions=CONVENTIONS" in script


def test_build_with_repo_override_embeds_conventions(tmp_path):
    """00012 + 00014: a per-repo override's `conventions` block is baked into
    the embedded prompt so the generated workflow honours the target's rules."""
    override = tmp_path / ".shiva.yml"
    override.write_text(
        "conventions: |\n"
        "  Prefer pure functions and never log secrets.\n"
        "categories:\n"
        "  - id: performance\n"
        "    enabled: false\n"
    )
    workflow = build_workflow(CONFIG_PATH, override_path=override)
    code = next(n for n in workflow["nodes"] if n["name"] == "Filter Diff & Build Prompt")
    script = code["parameters"]["pythonCode"]
    assert "Prefer pure functions and never log secrets." in script


def test_code_node_splits_large_prs_into_batches(workflow):
    """00011: the embedded logic packs the diff into size-bounded batches and
    emits one output item per batch, so n8n reviews a large PR in several
    passes (one Claude call + one comment per batch)."""
    code = next(n for n in workflow["nodes"] if n["name"] == "Filter Diff & Build Prompt")
    script = code["parameters"]["pythonCode"]
    assert "def split_files_into_batches(" in script
    assert "DEFAULT_MAX_BATCH_CHARS" in script
    # the node body fans out: one item per batch, each carrying batch metadata
    assert "split_files_into_batches(" in script
    assert "batch_count" in script
    # lineage pinned to the single webhook item so downstream $('...').item resolves
    assert "pairedItem" in script


def test_llm_node_uses_current_anthropic_api(workflow):
    llm = [
        n
        for n in node_by_type(workflow, "n8n-nodes-base.httpRequest")
        if "anthropic" in n["parameters"]["url"]
    ][0]
    body = llm["parameters"]["jsonBody"]
    assert "claude-opus-4-8" in body
    assert '"adaptive"' in body  # adaptive thinking, no budget_tokens
    assert "budget_tokens" not in body
    headers = {
        h["name"]: h["value"]
        for h in llm["parameters"]["headerParameters"]["parameters"]
    }
    assert headers["anthropic-version"] == "2023-06-01"


# --- AI Agent variant (task 00013) -----------------------------------------


def test_agent_variant_does_not_change_the_default_workflow():
    """--agent is opt-in: the default workflow must stay byte-identical so its
    committed artifact and CI staleness check are unaffected."""
    assert build_workflow(CONFIG_PATH, agent=False) == build_workflow(CONFIG_PATH)
    assert build_workflow(CONFIG_PATH, agent=True) != build_workflow(CONFIG_PATH)


def test_agent_workflow_replaces_the_llm_call_with_an_agent(agent_workflow):
    types = [n["type"] for n in agent_workflow["nodes"]]
    assert "@n8n/n8n-nodes-langchain.agent" in types
    assert "@n8n/n8n-nodes-langchain.lmChatAnthropic" in types
    assert "@n8n/n8n-nodes-langchain.toolHttpRequest" in types
    # the single-call Claude Review HTTP node is gone in this variant
    assert not any(
        n["type"] == "n8n-nodes-base.httpRequest" and "anthropic" in n["parameters"]["url"]
        for n in agent_workflow["nodes"]
    )


def test_agent_workflow_reuses_the_skip_and_filter_pipeline(agent_workflow):
    """The upstream gate + fetch + build-prompt Code nodes are identical to the
    default variant; only the review/comment stage changes."""
    types = [n["type"] for n in agent_workflow["nodes"]]
    assert "n8n-nodes-base.webhook" in types
    assert "n8n-nodes-base.if" in types
    assert types.count("n8n-nodes-base.code") == 2  # check skip + build prompt
    connections = agent_workflow["connections"]
    assert connections["Filter Diff & Build Prompt"]["main"][0][0]["node"] == "AI Review Agent"
    assert connections["AI Review Agent"]["main"][0][0]["node"] == "Post PR Comment"


def test_agent_model_and_tool_attach_via_langchain_connection_types(agent_workflow):
    connections = agent_workflow["connections"]
    model = connections["Anthropic Chat Model"]["ai_languageModel"][0][0]
    assert model["node"] == "AI Review Agent"
    assert model["type"] == "ai_languageModel"
    tool = connections["Fetch Repo File"]["ai_tool"][0][0]
    assert tool["node"] == "AI Review Agent"
    assert tool["type"] == "ai_tool"


def test_agent_carries_the_file_fetch_system_prompt(agent_workflow):
    from shiva_agent.review import FETCH_FILE_TOOL_NAME

    agent = next(n for n in agent_workflow["nodes"] if n["name"] == "AI Review Agent")
    system = agent["parameters"]["options"]["systemMessage"]
    assert FETCH_FILE_TOOL_NAME in system
    # the same fully-specified review prompt is still the user message
    assert agent["parameters"]["text"] == "={{ $json.prompt }}"


def test_fetch_tool_reads_the_head_sha_from_the_webhook(agent_workflow):
    """The tool must fetch files at the PR's head commit (the code under review),
    with owner/repo/sha resolved from the original webhook event."""
    tool = next(n for n in agent_workflow["nodes"] if n["name"] == "Fetch Repo File")
    url = tool["parameters"]["url"]
    assert "/contents/{path}" in url  # AI-supplied path placeholder
    assert "head.sha" in url  # pinned to the reviewed commit, not a branch tip
    assert "repository.full_name" in url
    placeholders = [p["name"] for p in tool["parameters"]["placeholderDefinitions"]["values"]]
    assert "path" in placeholders


def test_agent_post_comment_reads_agent_output(agent_workflow):
    """The agent emits plain text on $json.output — the comment body must read
    that, not the raw Anthropic messages `content` array of the default variant."""
    post = next(n for n in agent_workflow["nodes"] if n["name"] == "Post PR Comment")
    body = post["parameters"]["jsonBody"]
    assert "$json.output" in body
    assert "$json.content" not in body


def test_agent_workflow_is_json_serializable(agent_workflow):
    json.dumps(agent_workflow)


def test_agent_workflow_connection_targets_exist(agent_workflow):
    names = {n["name"] for n in agent_workflow["nodes"]}
    for source, targets in agent_workflow["connections"].items():
        assert source in names
        for conn_type in targets.values():
            for branch in conn_type:
                for target in branch:
                    assert target["node"] in names
