import json
from pathlib import Path

import pytest

from build_workflow import build_workflow

REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = REPO_ROOT / "shiva.config.yml"


@pytest.fixture(scope="module")
def workflow():
    return build_workflow(CONFIG_PATH)


def node_by_type(workflow, node_type):
    return [n for n in workflow["nodes"] if n["type"] == node_type]


def test_workflow_is_json_serializable(workflow):
    json.dumps(workflow)


def test_has_expected_nodes(workflow):
    types = [n["type"] for n in workflow["nodes"]]
    assert "n8n-nodes-base.webhook" in types
    assert types.count("n8n-nodes-base.httpRequest") == 3  # fetch files, LLM, post comment
    assert types.count("n8n-nodes-base.code") == 2  # check skip, build prompt
    assert "n8n-nodes-base.if" in types


def test_nodes_are_connected_in_a_chain(workflow):
    connections = workflow["connections"]
    names = {n["name"] for n in workflow["nodes"]}
    for source, targets in connections.items():
        assert source in names
        for branch in targets["main"]:
            for target in branch:
                assert target["node"] in names
    # every node except the last one has an outgoing connection
    assert len(connections) == len(workflow["nodes"]) - 1


def test_skip_check_runs_before_any_github_call(workflow):
    """00010: draft / skip-review PRs are dropped before Fetch PR Files."""
    connections = workflow["connections"]
    check = connections["GitHub PR Webhook"]["main"][0][0]["node"]
    assert check == "Check Skip Conditions"
    assert connections["Check Skip Conditions"]["main"][0][0]["node"] == "Skip Draft & Labeled PRs?"
    if_branches = connections["Skip Draft & Labeled PRs?"]["main"]
    assert if_branches[0][0]["node"] == "Fetch PR Files"  # true branch: continue
    assert if_branches[1] == []  # false branch: stop, no review


def test_check_skip_node_embeds_tested_predicate(workflow):
    check = next(n for n in workflow["nodes"] if n["name"] == "Check Skip Conditions")
    script = check["parameters"]["pythonCode"]
    assert check["parameters"]["language"] == "python"
    assert "def should_skip_pr(" in script
    assert "skip-review" in script
    # the reviewable-action allowlist must travel with the predicate
    assert "REVIEWABLE_ACTIONS" in script
    assert "ready_for_review" in script
    # the webhook body must be passed through for downstream $json.body expressions
    assert '"body"' in script


def test_if_node_routes_on_computed_skip_flag(workflow):
    if_node = node_by_type(workflow, "n8n-nodes-base.if")[0]
    conditions = if_node["parameters"]["conditions"]["conditions"]
    assert len(conditions) == 1
    assert conditions[0]["leftValue"] == "={{ $json.skip }}"
    assert conditions[0]["operator"] == {"type": "boolean", "operation": "false", "singleValue": True}


def test_python_nodes_use_native_runner_api(workflow):
    """n8n's native Python task runner exposes `_items` only; `_input` is
    the removed Pyodide API and fails at runtime with NameError."""
    for node in node_by_type(workflow, "n8n-nodes-base.code"):
        script = node["parameters"]["pythonCode"]
        assert "_items" in script, node["name"]
        assert "_input" not in script, node["name"]


def test_code_node_embeds_only_enabled_categories(workflow):
    code = next(n for n in workflow["nodes"] if n["name"] == "Filter Diff & Build Prompt")
    script = code["parameters"]["pythonCode"]
    for name in [
        "Structural Review",
        "Logical Review",
        "Behavioral Review",
        "Security Review",
        "Performance Review",
    ]:
        assert name in script
    for name in [
        "Code Style Review",
        "Docstrings and Comments Review",
        "Messages Review",
        "Test Coverage Review",
    ]:
        assert name not in script


def test_node_positions_are_derived_from_list_index(workflow):
    """Canvas positions are a function of order (220 * i), not hand-maintained
    literals, so inserting a node never requires rewriting downstream ones."""
    for i, node in enumerate(workflow["nodes"]):
        assert node["position"] == [220 * i, 0], node["name"]


def test_code_nodes_share_the_generated_template(workflow):
    """Both Python Code nodes are produced by one render helper, so the header,
    the native-runner comment, and the glue stay identical across them."""
    header = "# Generated by scripts/build_workflow.py — do not edit here."
    runner_comment = "# n8n native Python runner exposes input as `_items` (plain dicts)."
    for node in node_by_type(workflow, "n8n-nodes-base.code"):
        script = node["parameters"]["pythonCode"]
        assert script.startswith(header + "\n"), node["name"]
        assert runner_comment in script, node["name"]


def test_llm_node_uses_current_anthropic_api(workflow):
    llm = [
        n
        for n in node_by_type(workflow, "n8n-nodes-base.httpRequest")
        if "anthropic" in n["parameters"]["url"]
    ][0]
    body = llm["parameters"]["jsonBody"]
    assert "claude-opus-4-8" in body
    assert '"adaptive"' in body  # adaptive thinking, no budget_tokens
    assert "budget_tokens" not in body
    headers = {
        h["name"]: h["value"]
        for h in llm["parameters"]["headerParameters"]["parameters"]
    }
    assert headers["anthropic-version"] == "2023-06-01"
