"""Generate the importable n8n workflow JSON from shiva.config.yml.

Single source of truth: review categories come from shiva.config.yml and the
Code-node logic comes from src/shiva_agent/review.py (embedded verbatim), so
the workflow never drifts from the tested code.

Usage: python scripts/build_workflow.py  →  writes workflows/pr_review.json
"""

import argparse
import inspect
import json
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from shiva_agent import review  # noqa: E402

OUTPUT_PATH = REPO_ROOT / "workflows" / "pr_review.json"
# The AI Agent variant (task 00013) is generated separately so the default
# MVP workflow above stays byte-identical and its CI staleness check is unaffected.
AGENT_OUTPUT_PATH = REPO_ROOT / "workflows" / "pr_review.agent.json"


def render_code_node(edit_hint, constants, functions, body):
    """Assemble the source for an n8n Python Code node from its parts.

    Shared by every Code node so the generated-file header, the native-runner
    convention (input arrives as `_items`), and the source-embedding glue live
    in exactly one place — a runner-API change touches only this function.

    `edit_hint` names the files to edit instead; `constants` and `functions`
    are literal source blocks (the latter typically from inspect.getsource);
    `body` is the node's entry-point code operating on `_items`.
    """
    return f"""# Generated by scripts/build_workflow.py — do not edit here.
# {edit_hint}
{constants}

{functions}

# n8n native Python runner exposes input as `_items` (plain dicts).
{body}
"""


def build_check_skip_script():
    """Compose the Python source for the 'Check Skip Conditions' Code node."""
    constants = f"""SKIP_REVIEW_LABEL = {json.dumps(review.SKIP_REVIEW_LABEL)}
REVIEWABLE_ACTIONS = frozenset({json.dumps(sorted(review.REVIEWABLE_ACTIONS))})"""
    body = """body = (_items[0].get("json") or {}).get("body") or {}
return [{"json": {"skip": should_skip_pr(body), "body": body}}]"""
    return render_code_node(
        "Edit src/shiva_agent/review.py, then regenerate.",
        constants,
        inspect.getsource(review.should_skip_pr),
        body,
    )


def build_gate_node_script(api):
    """Compose the Python source for the 'Skip Empty Review' gate Code node.

    Reads the single LLM Review response and, when it names nothing to act on
    (the NO_FINDINGS_SENTINEL alone), emits no items so n8n skips Post PR Comment
    — the post/skip decision comes from ONE LLM call, no extra tokens. Otherwise
    passes the response through unchanged so Post PR Comment's expression works.
    """
    constants = (
        f"SEVERITY_LEVELS = {json.dumps(review.SEVERITY_LEVELS, indent=2)}\n"
        f"NO_FINDINGS_SENTINEL = {json.dumps(review.NO_FINDINGS_SENTINEL)}\n"
        f"LLM_API = {json.dumps(api)}"
    )
    functions = (
        inspect.getsource(review.extract_review_text)
        + "\n"
        + inspect.getsource(review.review_has_action_items)
    )
    body = (
        'resp = (_items[0].get("json") if _items else {}) or {}\n'
        "if review_has_action_items(extract_review_text(resp, LLM_API)):\n"
        "    return _items\n"
        "return []"
    )
    return render_code_node(
        "Edit src/shiva_agent/review.py, then regenerate.", constants, functions, body
    )


def build_code_node_script(enabled_categories, conventions="", exclude_globs=None):
    """Compose the Python source for the n8n Code node (Python runtime)."""
    functions = (
        # match_glob must precede filter_files, which calls it. It replaces a
        # `from fnmatch import fnmatch` the Python runner sandbox rejects (it
        # disallows every stdlib import) — see review.match_glob (task 00017).
        inspect.getsource(review.match_glob)
        + "\n"
        + inspect.getsource(review.filter_files)
        + "\n"
        + inspect.getsource(review.split_files_into_batches)
        + "\n"
        + inspect.getsource(review.build_review_prompt)
    )
    constants = f"""CATEGORIES = {json.dumps(enabled_categories, indent=2)}

# Severity scale + per-repo conventions baked into the prompt (task 00012).
SEVERITY_LEVELS = {json.dumps(review.SEVERITY_LEVELS, indent=2)}
# The no-findings sentinel build_review_prompt instructs the model to return.
NO_FINDINGS_SENTINEL = {json.dumps(review.NO_FINDINGS_SENTINEL)}
CONVENTIONS = {json.dumps(conventions)}

ALLOWED_EXTENSIONS = None  # e.g. [".py"] to review Python files only
# Skip generated / vendored / lock files before review (task 00017); globs are
# matched against the full path and the basename. From shiva.config.yml.
EXCLUDE_GLOBS = {json.dumps(exclude_globs or [], indent=2)}
DEFAULT_MAX_PATCH_CHARS = 15_000
# Total patch budget per review pass; a large PR is split across passes (00011).
DEFAULT_MAX_BATCH_CHARS = {review.DEFAULT_MAX_BATCH_CHARS}"""
    # One output item per batch → n8n fans out (one Claude call + one comment
    # per batch). Every item's lineage is pinned to the single webhook item so
    # 'Post PR Comment' can still resolve $('GitHub PR Webhook').item.
    body = """files = [item.get("json") or {} for item in _items]
kept = filter_files(files, allowed_extensions=ALLOWED_EXTENSIONS, exclude_globs=EXCLUDE_GLOBS)
if not kept:
    # Every changed file was filtered out — binary, removed, oversized, or an
    # excluded generated/vendored/lock file (task 00017). Emit no items so n8n
    # skips the Claude call and Post PR Comment entirely (task 00018): no paid
    # review and no noise comment on a PR with nothing to review, mirroring the
    # empty false-branch of the skip gate (task 00010).
    return []
batches = split_files_into_batches(kept, max_batch_chars=DEFAULT_MAX_BATCH_CHARS)
out = []
for i, batch in enumerate(batches):
    prompt = build_review_prompt(
        CATEGORIES, batch, conventions=CONVENTIONS, part=(i + 1, len(batches))
    )
    out.append({
        "json": {
            "prompt": prompt,
            "batch_index": i + 1,
            "batch_count": len(batches),
            "reviewed_files": len(batch),
            "total_files": len(files),
        },
        "pairedItem": {"item": 0},
    })
return out"""
    return render_code_node(
        "Edit src/shiva_agent/review.py and shiva.config.yml, then regenerate.",
        constants,
        functions,
        body,
    )


# --- AI Agent variant (task 00013) -----------------------------------------
# The default workflow reviews the diff in a single stateless HTTP call to the
# Anthropic API. The agent variant swaps that node for an n8n AI Agent that runs
# the model in a tool-use loop with a `fetch_repo_file` tool, so it can pull
# extra files from the target repo for context. Everything upstream (skip gate,
# fetch files, filter/build-prompt Code node) is reused unchanged.
#
# NOTE: the LangChain node type ids and typeVersions below are best-effort and
# are NOT verifiable without a live n8n LangChain runtime; confirming the agent
# actually loads and fans out is folded into the E2E task 00008.
AGENT_NODE = "AI Review Agent"
CHAT_MODEL_NODE = "Chat Model"
FETCH_FILE_TOOL_NODE = "Fetch Repo File"


def build_agent_node():
    """The AI Agent node: reviews the prompt, may call the file-fetch tool."""
    return {
        "id": "review_agent",
        "name": AGENT_NODE,
        "type": "@n8n/n8n-nodes-langchain.agent",
        "typeVersion": 1.9,
        "position": None,
        "parameters": {
            "promptType": "define",
            # The user message is the same fully-specified review prompt the
            # default workflow builds (categories + severity + output format).
            "text": "={{ $json.prompt }}",
            "options": {"systemMessage": review.build_agent_system_prompt()},
        },
        "notes": "Task 00013: agentic review — the model can call the file-fetch tool for extra context.",
    }


def build_chat_model_node(llm):
    """Chat-model sub-node feeding the agent (ai_languageModel), per provider.

    The wire-protocol object (`LLMApi`) picks the LangChain node type and params
    — `lmChatAnthropic` for the Anthropic API, `lmChatOpenAi` (with the base URL)
    for every OpenAI-compatible provider — so the agent variant follows the same
    vendor-agnostic layer as the single-call review (task 00020).
    """
    spec = review.LLM_APIS[llm["api"]].agent_chat_node(llm["model"], llm["endpoint"])
    auth_header, value_hint = review.llm_auth(llm["auth"])
    cred = (
        f"no API key ({llm['provider']} is local/keyless)"
        if auth_header is None
        else f"credential '{auth_header}' = '{value_hint}'"
    )
    return {
        "id": "chat_model",
        "name": CHAT_MODEL_NODE,
        "type": spec["type"],
        "typeVersion": spec["typeVersion"],
        "position": None,
        "parameters": spec["parameters"],
        "notes": f"LLM: {llm['provider']} ({llm['model']}); {cred}.",
    }


def build_fetch_file_tool_node():
    """HTTP Request tool the agent calls to fetch a repo file at the head SHA.

    The model supplies a repository-relative path via the `{path}` placeholder;
    owner/repo and the head commit come from the original webhook event, so the
    tool always reads the exact code under review. `raw+json` returns the file
    body as plain text rather than base64-wrapped JSON.
    """
    full_name = "$('GitHub PR Webhook').item.json.body.repository.full_name"
    head_sha = "$('GitHub PR Webhook').item.json.body.pull_request.head.sha"
    return {
        "id": "fetch_file_tool",
        "name": FETCH_FILE_TOOL_NODE,
        "type": "@n8n/n8n-nodes-langchain.toolHttpRequest",
        "typeVersion": 1.1,
        "position": None,
        "parameters": {
            "toolDescription": review.FETCH_FILE_TOOL_DESCRIPTION,
            "method": "GET",
            "url": (
                "=https://api.github.com/repos/{{ " + full_name + " }}"
                "/contents/{path}?ref={{ " + head_sha + " }}"
            ),
            "authentication": "genericCredentialType",
            "genericAuthType": "httpHeaderAuth",
            "sendHeaders": True,
            "headerParameters": {
                "parameters": [
                    {"name": "Accept", "value": "application/vnd.github.raw+json"},
                    {"name": "User-Agent", "value": "shiva-pr-review-agent"},
                ]
            },
            "placeholderDefinitions": {
                "values": [
                    {
                        "name": "path",
                        "description": "repository-relative file path to fetch, e.g. src/app/main.py",
                        "type": "string",
                    }
                ]
            },
        },
        "notes": "Same GitHub PAT credential as 'Fetch PR Files' (task 00002).",
    }


# --- Provider-agnostic review node (task 00019) -----------------------------
# The MVP hard-wired the review to Anthropic's Messages API. These helpers build
# the single-call review node and the comment-extraction expression from the
# resolved `llm` settings instead, so the same workflow can target Anthropic,
# OpenAI, DeepSeek, Qwen, or a local Ollama by config alone.


def build_review_request_body(llm):
    """The JSON body for the review HTTP call, as an n8n expression string.

    The wire-protocol object (`LLMApi`) owns the body shape; here we only render
    it and splice in the prompt via ``JSON.stringify($json.prompt)`` so it is
    safely escaped.
    """
    body = review.LLM_APIS[llm["api"]].request_body(
        llm["model"], temperature=llm.get("temperature", review.DEFAULT_TEMPERATURE)
    )
    rendered = json.dumps(body, indent=2).replace(
        f'"{review.PROMPT_SENTINEL}"', "{{ JSON.stringify($json.prompt) }}"
    )
    return "=" + rendered  # n8n expressions require a leading '='


def build_review_comment_body(llm):
    """The n8n expression that extracts the review text into a comment body."""
    return review.LLM_APIS[llm["api"]].comment_body_expr()


def build_review_node(llm):
    """The single-call review HTTP node, targeting the configured provider."""
    api = review.LLM_APIS[llm["api"]]
    auth_header, value_hint = review.llm_auth(llm["auth"])
    if auth_header is None:
        cred_note = f"No API key required ({llm['provider']} is local/keyless)."
    else:
        cred_note = f"Credential: HTTP Header Auth '{auth_header}' = '{value_hint}'."
    node = {
        "id": "llm_review",
        "name": "LLM Review",
        "type": "n8n-nodes-base.httpRequest",
        "typeVersion": 4.2,
        "position": None,
        "parameters": {
            "method": "POST",
            "url": llm["endpoint"],
            "sendHeaders": True,
            "headerParameters": {"parameters": api.http_headers()},
            "sendBody": True,
            "specifyBody": "json",
            "jsonBody": build_review_request_body(llm),
        },
        "notes": f"LLM: {llm['provider']} ({llm['model']}). {cred_note}",
    }
    if auth_header is not None:
        node["parameters"]["authentication"] = "genericCredentialType"
        node["parameters"]["genericAuthType"] = "httpHeaderAuth"
    return node


def build_workflow(config_path, override_path=None, agent=False, repo=None):
    """Build the n8n workflow from the default config.

    When `override_path` points at a target repo's `.shiva.yml`, its categories
    are merged over the defaults by `id` (task 00014) before being embedded, so
    a per-repo review configuration can be baked into a repo-specific workflow.

    When `repo` (an ``owner/name``) is given, the LLM provider is resolved from
    the config's `llm_by_repo` mapping — the "default model + per-repo models"
    map — falling back to the default `llm`. Because n8n bakes the provider into
    the node, each mapped repo gets its own built workflow.

    When `agent` is true, the single-call `LLM Review` node is replaced by an
    AI Agent node wired to a chat model and a `fetch_repo_file` tool, so the
    model can request extra repository files for context (task 00013). The
    upstream skip-gate / fetch / filter pipeline is identical in both variants.
    """
    config = yaml.safe_load(Path(config_path).read_text())
    override = yaml.safe_load(Path(override_path).read_text()) if override_path else None
    enabled = review.resolve_categories(config, override)
    conventions = review.resolve_conventions(config, override)
    exclude_globs = review.resolve_exclude(config, override)
    llm = review.resolve_llm(config, override, repo=repo)

    webhook = {
        "id": "webhook",
        "name": "GitHub PR Webhook",
        "type": "n8n-nodes-base.webhook",
        "typeVersion": 2,
        # required for n8n to register the webhook on activation; stable so
        # re-imports keep the same production URL
        "webhookId": "c0ffee00-5417-4a11-9e57-5b1de0a5c0de",
        # placeholder; canvas position is derived from list index below
        "position": None,
        "parameters": {
            "httpMethod": "POST",
            "path": "pr-review",
            "options": {},
        },
    }

    check_skip = {
        "id": "check_skip",
        "name": "Check Skip Conditions",
        "type": "n8n-nodes-base.code",
        "typeVersion": 2,
        "position": None,
        "parameters": {
            "language": "python",
            "pythonCode": build_check_skip_script(),
        },
        "notes": "Task 00010: computes skip=true for draft PRs and PRs labeled 'skip-review'.",
    }

    skip_gate = {
        "id": "skip_gate",
        "name": "Skip Draft & Labeled PRs?",
        "type": "n8n-nodes-base.if",
        "typeVersion": 2.2,
        "position": None,
        "parameters": {
            "conditions": {
                "options": {
                    "caseSensitive": True,
                    "leftValue": "",
                    "typeValidation": "strict",
                    "version": 2,
                },
                "combinator": "and",
                "conditions": [
                    {
                        "leftValue": "={{ $json.skip }}",
                        "rightValue": "",
                        "operator": {
                            "type": "boolean",
                            "operation": "false",
                            "singleValue": True,
                        },
                    }
                ],
            },
            "options": {},
        },
        "notes": "True branch continues to review; false branch ends the run without comments.",
    }

    fetch_files = {
        "id": "fetch_files",
        "name": "Fetch PR Files",
        "type": "n8n-nodes-base.httpRequest",
        "typeVersion": 4.2,
        "position": None,
        "parameters": {
            "url": "=https://api.github.com/repos/{{ $json.body.repository.full_name }}/pulls/{{ $json.body.pull_request.number }}/files",
            "authentication": "genericCredentialType",
            "genericAuthType": "httpHeaderAuth",
            "sendHeaders": True,
            "headerParameters": {
                "parameters": [
                    {"name": "Accept", "value": "application/vnd.github+json"},
                    {"name": "User-Agent", "value": "shiva-pr-review-agent"},
                ]
            },
            "options": {},
        },
        "notes": "Credential: HTTP Header Auth with name 'Authorization', value 'Bearer <GitHub PAT>' (task 00002).",
    }

    code = {
        "id": "build_prompt",
        "name": "Filter Diff & Build Prompt",
        "type": "n8n-nodes-base.code",
        "typeVersion": 2,
        "position": None,
        "parameters": {
            "language": "python",
            "pythonCode": build_code_node_script(enabled, conventions, exclude_globs),
        },
    }

    review_node = build_review_node(llm)

    post_comment = {
        "id": "post_comment",
        "name": "Post PR Comment",
        "type": "n8n-nodes-base.httpRequest",
        "typeVersion": 4.2,
        "position": None,
        "parameters": {
            "method": "POST",
            "url": "=https://api.github.com/repos/{{ $('GitHub PR Webhook').item.json.body.repository.full_name }}/issues/{{ $('GitHub PR Webhook').item.json.body.pull_request.number }}/comments",
            "authentication": "genericCredentialType",
            "genericAuthType": "httpHeaderAuth",
            "sendHeaders": True,
            "headerParameters": {
                "parameters": [
                    {"name": "Accept", "value": "application/vnd.github+json"},
                    {"name": "User-Agent", "value": "shiva-pr-review-agent"},
                ]
            },
            "sendBody": True,
            "specifyBody": "json",
            "jsonBody": build_review_comment_body(llm),
            "options": {},
        },
        "notes": "Same GitHub PAT credential as 'Fetch PR Files'.",
    }

    # Nodes shared by both variants (webhook → skip gate → fetch → build prompt).
    prefix = [webhook, check_skip, skip_gate, fetch_files, code]
    common_connections = {
        "GitHub PR Webhook": {"main": [[{"node": "Check Skip Conditions", "type": "main", "index": 0}]]},
        "Check Skip Conditions": {"main": [[{"node": "Skip Draft & Labeled PRs?", "type": "main", "index": 0}]]},
        # IF node: output 0 = true (skip == false → review), output 1 = false (skip → stop)
        "Skip Draft & Labeled PRs?": {
            "main": [
                [{"node": "Fetch PR Files", "type": "main", "index": 0}],
                [],
            ]
        },
        "Fetch PR Files": {"main": [[{"node": "Filter Diff & Build Prompt", "type": "main", "index": 0}]]},
    }

    if agent:
        review_agent = build_agent_node()
        chat_model = build_chat_model_node(llm)
        fetch_tool = build_fetch_file_tool_node()
        # The agent emits its answer as plain text on $json.output.
        agent_post_comment = dict(post_comment)
        agent_post_comment["parameters"] = dict(post_comment["parameters"])
        agent_post_comment["parameters"]["jsonBody"] = (
            "={{ JSON.stringify({ body: $json.output }) }}"
        )

        main_chain = prefix + [review_agent, agent_post_comment]
        for i, node in enumerate(main_chain):
            node["position"] = [220 * i, 0]
        # Sub-nodes hang below the agent (position is cosmetic on the canvas).
        chat_model["position"] = [review_agent["position"][0] - 80, 220]
        fetch_tool["position"] = [review_agent["position"][0] + 120, 220]
        nodes = main_chain + [chat_model, fetch_tool]

        connections = dict(common_connections)
        connections["Filter Diff & Build Prompt"] = {
            "main": [[{"node": AGENT_NODE, "type": "main", "index": 0}]]
        }
        connections[AGENT_NODE] = {"main": [[{"node": "Post PR Comment", "type": "main", "index": 0}]]}
        # Sub-nodes attach to the agent via the LangChain connection types.
        connections[CHAT_MODEL_NODE] = {
            "ai_languageModel": [[{"node": AGENT_NODE, "type": "ai_languageModel", "index": 0}]]
        }
        connections[FETCH_FILE_TOOL_NODE] = {
            "ai_tool": [[{"node": AGENT_NODE, "type": "ai_tool", "index": 0}]]
        }
        return {
            "id": "ShivaPrReviewAgent001",
            "name": "Shiva PR Review Agent (agentic)",
            "nodes": nodes,
            "connections": connections,
            "settings": {"executionOrder": "v1"},
            "active": False,
        }

    # Gate: post the comment only when the single LLM Review names something to
    # act on; otherwise emit no items so n8n skips Post PR Comment (no noise, no
    # wasted GitHub call). Same empty-items skip mechanism as the diff filter.
    skip_empty = {
        "id": "skip_empty_review",
        "name": "Skip Empty Review",
        "type": "n8n-nodes-base.code",
        "typeVersion": 2,
        "position": None,
        "parameters": {
            "language": "python",
            "pythonCode": build_gate_node_script(llm["api"]),
        },
        "notes": "Post only when the review has action items; a bare "
        f"'{review.NO_FINDINGS_SENTINEL}' emits no items so Post PR Comment is skipped.",
    }

    nodes = prefix + [review_node, skip_empty, post_comment]
    # Lay the nodes out left-to-right in execution order; deriving each position
    # from its index means inserting a node never rewrites downstream ones.
    for i, node in enumerate(nodes):
        node["position"] = [220 * i, 0]

    connections = dict(common_connections)
    connections["Filter Diff & Build Prompt"] = {
        "main": [[{"node": "LLM Review", "type": "main", "index": 0}]]
    }
    connections["LLM Review"] = {"main": [[{"node": "Skip Empty Review", "type": "main", "index": 0}]]}
    connections["Skip Empty Review"] = {"main": [[{"node": "Post PR Comment", "type": "main", "index": 0}]]}

    return {
        "id": "ShivaPrReview001",
        "name": "Shiva PR Review Agent",
        "nodes": nodes,
        "connections": connections,
        "settings": {"executionOrder": "v1"},
        "active": False,
    }


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--override",
        metavar="PATH",
        help="a target repo's .shiva.yml, merged over the defaults by category id",
    )
    parser.add_argument(
        "--agent",
        action="store_true",
        help="build the AI Agent variant (model can fetch extra repo files, task 00013)",
    )
    parser.add_argument(
        "--repo",
        metavar="OWNER/NAME",
        default=None,
        help="resolve the LLM from the config's llm_by_repo mapping for this repo",
    )
    parser.add_argument(
        "-o",
        "--output",
        metavar="PATH",
        default=None,
        type=Path,
        help="where to write the workflow JSON "
        f"(default: {OUTPUT_PATH.relative_to(REPO_ROOT)}, "
        f"or {AGENT_OUTPUT_PATH.relative_to(REPO_ROOT)} with --agent)",
    )
    args = parser.parse_args(argv)

    output = args.output or (AGENT_OUTPUT_PATH if args.agent else OUTPUT_PATH)
    try:
        workflow = build_workflow(
            REPO_ROOT / "shiva.config.yml",
            override_path=args.override,
            agent=args.agent,
            repo=args.repo,
        )
    except review.ConfigError as exc:
        # A malformed config (usually a hand-written --override .shiva.yml) should
        # fail the build with an actionable one-liner, not a traceback (task 00015).
        source = args.override or "shiva.config.yml"
        parser.exit(2, f"error: invalid config in {source}: {exc}\n")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(workflow, indent=2) + "\n")
    print(f"wrote {output}")


if __name__ == "__main__":
    main()
