"""Generate the importable n8n workflow JSON from shiva.config.yml.

Single source of truth: review categories come from shiva.config.yml and the
Code-node logic comes from src/shiva_agent/review.py (embedded verbatim), so
the workflow never drifts from the tested code.

Usage: python scripts/build_workflow.py  →  writes workflows/pr_review.json
"""

import argparse
import inspect
import json
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from shiva_agent import review  # noqa: E402

OUTPUT_PATH = REPO_ROOT / "workflows" / "pr_review.json"

ANTHROPIC_MODEL = "claude-opus-4-8"


def render_code_node(edit_hint, constants, functions, body):
    """Assemble the source for an n8n Python Code node from its parts.

    Shared by every Code node so the generated-file header, the native-runner
    convention (input arrives as `_items`), and the source-embedding glue live
    in exactly one place — a runner-API change touches only this function.

    `edit_hint` names the files to edit instead; `constants` and `functions`
    are literal source blocks (the latter typically from inspect.getsource);
    `body` is the node's entry-point code operating on `_items`.
    """
    return f"""# Generated by scripts/build_workflow.py — do not edit here.
# {edit_hint}
{constants}

{functions}

# n8n native Python runner exposes input as `_items` (plain dicts).
{body}
"""


def build_check_skip_script():
    """Compose the Python source for the 'Check Skip Conditions' Code node."""
    constants = f"""SKIP_REVIEW_LABEL = {json.dumps(review.SKIP_REVIEW_LABEL)}
REVIEWABLE_ACTIONS = frozenset({json.dumps(sorted(review.REVIEWABLE_ACTIONS))})"""
    body = """body = (_items[0].get("json") or {}).get("body") or {}
return [{"json": {"skip": should_skip_pr(body), "body": body}}]"""
    return render_code_node(
        "Edit src/shiva_agent/review.py, then regenerate.",
        constants,
        inspect.getsource(review.should_skip_pr),
        body,
    )


def build_code_node_script(enabled_categories, conventions=""):
    """Compose the Python source for the n8n Code node (Python runtime)."""
    functions = (
        inspect.getsource(review.filter_files)
        + "\n"
        + inspect.getsource(review.split_files_into_batches)
        + "\n"
        + inspect.getsource(review.build_review_prompt)
    )
    constants = f"""CATEGORIES = {json.dumps(enabled_categories, indent=2)}

# Severity scale + per-repo conventions baked into the prompt (task 00012).
SEVERITY_LEVELS = {json.dumps(review.SEVERITY_LEVELS, indent=2)}
CONVENTIONS = {json.dumps(conventions)}

ALLOWED_EXTENSIONS = None  # e.g. [".py"] to review Python files only
DEFAULT_MAX_PATCH_CHARS = 15_000
# Total patch budget per review pass; a large PR is split across passes (00011).
DEFAULT_MAX_BATCH_CHARS = {review.DEFAULT_MAX_BATCH_CHARS}"""
    # One output item per batch → n8n fans out (one Claude call + one comment
    # per batch). Every item's lineage is pinned to the single webhook item so
    # 'Post PR Comment' can still resolve $('GitHub PR Webhook').item.
    body = """files = [item.get("json") or {} for item in _items]
kept = filter_files(files, allowed_extensions=ALLOWED_EXTENSIONS)
batches = split_files_into_batches(kept, max_batch_chars=DEFAULT_MAX_BATCH_CHARS)
out = []
for i, batch in enumerate(batches):
    prompt = build_review_prompt(
        CATEGORIES, batch, conventions=CONVENTIONS, part=(i + 1, len(batches))
    )
    out.append({
        "json": {
            "prompt": prompt,
            "batch_index": i + 1,
            "batch_count": len(batches),
            "reviewed_files": len(batch),
            "total_files": len(files),
        },
        "pairedItem": {"item": 0},
    })
return out"""
    return render_code_node(
        "Edit src/shiva_agent/review.py and shiva.config.yml, then regenerate.",
        constants,
        functions,
        body,
    )


def build_workflow(config_path, override_path=None):
    """Build the n8n workflow from the default config.

    When `override_path` points at a target repo's `.shiva.yml`, its categories
    are merged over the defaults by `id` (task 00014) before being embedded, so
    a per-repo review configuration can be baked into a repo-specific workflow.
    """
    config = yaml.safe_load(Path(config_path).read_text())
    override = yaml.safe_load(Path(override_path).read_text()) if override_path else None
    enabled = review.resolve_categories(config, override)
    conventions = review.resolve_conventions(config, override)

    webhook = {
        "id": "webhook",
        "name": "GitHub PR Webhook",
        "type": "n8n-nodes-base.webhook",
        "typeVersion": 2,
        # required for n8n to register the webhook on activation; stable so
        # re-imports keep the same production URL
        "webhookId": "c0ffee00-5417-4a11-9e57-5b1de0a5c0de",
        # placeholder; canvas position is derived from list index below
        "position": None,
        "parameters": {
            "httpMethod": "POST",
            "path": "pr-review",
            "options": {},
        },
    }

    check_skip = {
        "id": "check_skip",
        "name": "Check Skip Conditions",
        "type": "n8n-nodes-base.code",
        "typeVersion": 2,
        "position": None,
        "parameters": {
            "language": "python",
            "pythonCode": build_check_skip_script(),
        },
        "notes": "Task 00010: computes skip=true for draft PRs and PRs labeled 'skip-review'.",
    }

    skip_gate = {
        "id": "skip_gate",
        "name": "Skip Draft & Labeled PRs?",
        "type": "n8n-nodes-base.if",
        "typeVersion": 2.2,
        "position": None,
        "parameters": {
            "conditions": {
                "options": {
                    "caseSensitive": True,
                    "leftValue": "",
                    "typeValidation": "strict",
                    "version": 2,
                },
                "combinator": "and",
                "conditions": [
                    {
                        "leftValue": "={{ $json.skip }}",
                        "rightValue": "",
                        "operator": {
                            "type": "boolean",
                            "operation": "false",
                            "singleValue": True,
                        },
                    }
                ],
            },
            "options": {},
        },
        "notes": "True branch continues to review; false branch ends the run without comments.",
    }

    fetch_files = {
        "id": "fetch_files",
        "name": "Fetch PR Files",
        "type": "n8n-nodes-base.httpRequest",
        "typeVersion": 4.2,
        "position": None,
        "parameters": {
            "url": "=https://api.github.com/repos/{{ $json.body.repository.full_name }}/pulls/{{ $json.body.pull_request.number }}/files",
            "authentication": "genericCredentialType",
            "genericAuthType": "httpHeaderAuth",
            "sendHeaders": True,
            "headerParameters": {
                "parameters": [
                    {"name": "Accept", "value": "application/vnd.github+json"},
                    {"name": "User-Agent", "value": "shiva-pr-review-agent"},
                ]
            },
            "options": {},
        },
        "notes": "Credential: HTTP Header Auth with name 'Authorization', value 'Bearer <GitHub PAT>' (task 00002).",
    }

    code = {
        "id": "build_prompt",
        "name": "Filter Diff & Build Prompt",
        "type": "n8n-nodes-base.code",
        "typeVersion": 2,
        "position": None,
        "parameters": {
            "language": "python",
            "pythonCode": build_code_node_script(enabled, conventions),
        },
    }

    llm = {
        "id": "llm_review",
        "name": "Claude Review",
        "type": "n8n-nodes-base.httpRequest",
        "typeVersion": 4.2,
        "position": None,
        "parameters": {
            "method": "POST",
            "url": "https://api.anthropic.com/v1/messages",
            "authentication": "genericCredentialType",
            "genericAuthType": "httpHeaderAuth",
            "sendHeaders": True,
            "headerParameters": {
                "parameters": [
                    {"name": "anthropic-version", "value": "2023-06-01"},
                    {"name": "content-type", "value": "application/json"},
                ]
            },
            "sendBody": True,
            "specifyBody": "json",
            "jsonBody": json.dumps(
                {
                    "model": ANTHROPIC_MODEL,
                    "max_tokens": 16000,
                    "thinking": {"type": "adaptive"},
                    "messages": [{"role": "user", "content": "{{ $json.prompt }}"}],
                },
                indent=2,
            ).replace('"{{ $json.prompt }}"', "{{ JSON.stringify($json.prompt) }}"),
        },
        "notes": "Credential: HTTP Header Auth with name 'x-api-key', value '<Anthropic API key>'.",
    }
    # n8n expressions require a leading '=' on the whole value
    llm["parameters"]["jsonBody"] = "=" + llm["parameters"]["jsonBody"]

    post_comment = {
        "id": "post_comment",
        "name": "Post PR Comment",
        "type": "n8n-nodes-base.httpRequest",
        "typeVersion": 4.2,
        "position": None,
        "parameters": {
            "method": "POST",
            "url": "=https://api.github.com/repos/{{ $('GitHub PR Webhook').item.json.body.repository.full_name }}/issues/{{ $('GitHub PR Webhook').item.json.body.pull_request.number }}/comments",
            "authentication": "genericCredentialType",
            "genericAuthType": "httpHeaderAuth",
            "sendHeaders": True,
            "headerParameters": {
                "parameters": [
                    {"name": "Accept", "value": "application/vnd.github+json"},
                    {"name": "User-Agent", "value": "shiva-pr-review-agent"},
                ]
            },
            "sendBody": True,
            "specifyBody": "json",
            "jsonBody": "={{ JSON.stringify({ body: $json.content.filter(b => b.type === 'text').map(b => b.text).join('\\n') }) }}",
            "options": {},
        },
        "notes": "Same GitHub PAT credential as 'Fetch PR Files'.",
    }

    nodes = [webhook, check_skip, skip_gate, fetch_files, code, llm, post_comment]
    # Lay the nodes out left-to-right in execution order; deriving each position
    # from its index means inserting a node never rewrites downstream ones.
    for i, node in enumerate(nodes):
        node["position"] = [220 * i, 0]

    connections = {
        "GitHub PR Webhook": {"main": [[{"node": "Check Skip Conditions", "type": "main", "index": 0}]]},
        "Check Skip Conditions": {"main": [[{"node": "Skip Draft & Labeled PRs?", "type": "main", "index": 0}]]},
        # IF node: output 0 = true (skip == false → review), output 1 = false (skip → stop)
        "Skip Draft & Labeled PRs?": {
            "main": [
                [{"node": "Fetch PR Files", "type": "main", "index": 0}],
                [],
            ]
        },
        "Fetch PR Files": {"main": [[{"node": "Filter Diff & Build Prompt", "type": "main", "index": 0}]]},
        "Filter Diff & Build Prompt": {"main": [[{"node": "Claude Review", "type": "main", "index": 0}]]},
        "Claude Review": {"main": [[{"node": "Post PR Comment", "type": "main", "index": 0}]]},
    }

    return {
        "id": "ShivaPrReview001",
        "name": "Shiva PR Review Agent",
        "nodes": nodes,
        "connections": connections,
        "settings": {"executionOrder": "v1"},
        "active": False,
    }


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--override",
        metavar="PATH",
        help="a target repo's .shiva.yml, merged over the defaults by category id",
    )
    parser.add_argument(
        "-o",
        "--output",
        metavar="PATH",
        default=OUTPUT_PATH,
        type=Path,
        help=f"where to write the workflow JSON (default: {OUTPUT_PATH.relative_to(REPO_ROOT)})",
    )
    args = parser.parse_args(argv)

    workflow = build_workflow(REPO_ROOT / "shiva.config.yml", override_path=args.override)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(workflow, indent=2) + "\n")
    print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
